# Generated by Django 5.1.7 on 2025-03-14 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='Дома', max_length=200, verbose_name='Место выполнения привычки')),
                ('habit_time', models.DateTimeField(verbose_name='Дата и время выполнения привычки')),
                ('action', models.CharField(max_length=200, verbose_name='Выполняемое действие')),
                ('nice_habit', models.BooleanField(blank=True, default=False, null=True, verbose_name='Приятная привычка')),
                ('period', models.PositiveIntegerField(blank=True, null=True, verbose_name='Период выполнения привычки')),
                ('award', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вознаграждение')),
                ('complete_time', models.DurationField(blank=True, null=True, verbose_name='Время на выполнение привычки')),
                ('is_public', models.BooleanField(blank=True, default=True, null=True, verbose_name='Публичность привычки')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habits', verbose_name='Связанная привычка')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец привычки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
