# Generated by Django 5.1.7 on 2025-03-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habits',
            old_name='owner',
            new_name='user',
        ),
    ]
